//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FraterniTree.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FraterniTree.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutBox.
        /// </summary>
        internal static string AboutBox {
            get {
                return ResourceManager.GetString("AboutBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Active Only*.
        /// </summary>
        internal static string ActiveOnlyFilter {
            get {
                return ResourceManager.GetString("ActiveOnlyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Active Only* Tree.
        /// </summary>
        internal static string ActiveOnlyTree {
            get {
                return ResourceManager.GetString("ActiveOnlyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Big.
        /// </summary>
        internal static string AddBig {
            get {
                return ResourceManager.GetString("AddBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Member:.
        /// </summary>
        internal static string AddMember {
            get {
                return ResourceManager.GetString("AddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *All*.
        /// </summary>
        internal static string AllFilter {
            get {
                return ResourceManager.GetString("AllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Image Files|*.png;*.bmp;*.gif;*.jpg;*.jpeg;*.jpe;*.jfif;*.tif;*.tiff|PNG|*.png|Bitmap|*.bmp|GIF|*.gif|JPEG|*.jpg;*.jpeg;*.jpe;*.jfif|TIFF|*.tif;*.tiff|All Files|*.*.
        /// </summary>
        internal static string AllImagesFilter {
            get {
                return ResourceManager.GetString("AllImagesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *All* Tree.
        /// </summary>
        internal static string AllTree {
            get {
                return ResourceManager.GetString("AllTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string AndAbout {
            get {
                return ResourceManager.GetString("AndAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add Member.
        /// </summary>
        internal static string AndAddMember {
            get {
                return ResourceManager.GetString("AndAddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Display Root of \&apos;*All*\&apos; Tree.
        /// </summary>
        internal static string AndDisplayRoot {
            get {
                return ResourceManager.GetString("AndDisplayRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export XML....
        /// </summary>
        internal static string AndExportXml {
            get {
                return ResourceManager.GetString("AndExportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string AndFile {
            get {
                return ResourceManager.GetString("AndFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Graphical Tree Control.
        /// </summary>
        internal static string AndGraphicalTreeControl {
            get {
                return ResourceManager.GetString("AndGraphicalTreeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string AndHelp {
            get {
                return ResourceManager.GetString("AndHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Members Without Bigs.
        /// </summary>
        internal static string AndMembersWithoutBigs {
            get {
                return ResourceManager.GetString("AndMembersWithoutBigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string AndOk {
            get {
                return ResourceManager.GetString("AndOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quit.
        /// </summary>
        internal static string AndQuit {
            get {
                return ResourceManager.GetString("AndQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Support... (Web Page).
        /// </summary>
        internal static string AndSupport {
            get {
                return ResourceManager.GetString("AndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tree View.
        /// </summary>
        internal static string AndTreeView {
            get {
                return ResourceManager.GetString("AndTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string AndView {
            get {
                return ResourceManager.GetString("AndView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Window.
        /// </summary>
        internal static string AndWindow {
            get {
                return ResourceManager.GetString("AndWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sav.
        /// </summary>
        internal static string AutoSaveFileExtension {
            get {
                return ResourceManager.GetString("AutoSaveFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big:.
        /// </summary>
        internal static string BigIs {
            get {
                return ResourceManager.GetString("BigIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brother.
        /// </summary>
        internal static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YitboSoft.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://yitbosoft.com/?contact.
        /// </summary>
        internal static string CompanyWebsite {
            get {
                return ResourceManager.GetString("CompanyWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server={0};port={1};userid={2};password={3};database={4};allow user variables=true.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Database.
        /// </summary>
        internal static string ConnectToDatabase {
            get {
                return ResourceManager.GetString("ConnectToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2016.
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Active?.
        /// </summary>
        internal static string CurrentlyActive {
            get {
                return ResourceManager.GetString("CurrentlyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this node: {0}?\n\n All its children nodes will be re-assigned to the parent..
        /// </summary>
        internal static string DeleteNodeConfirmation {
            get {
                return ResourceManager.GetString("DeleteNodeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .BAK.
        /// </summary>
        internal static string DotBak {
            get {
                return ResourceManager.GetString("DotBak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sav.
        /// </summary>
        internal static string DotSav {
            get {
                return ResourceManager.GetString("DotSav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        internal static string DotXml {
            get {
                return ResourceManager.GetString("DotXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall.
        /// </summary>
        internal static string Fall {
            get {
                return ResourceManager.GetString("Fall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorori.
        /// </summary>
        internal static string FemaleName {
            get {
                return ResourceManager.GetString("FemaleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string FirstNameIs {
            get {
                return ResourceManager.GetString("FirstNameIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Label Widths.
        /// </summary>
        internal static string FixedLabelWidths {
            get {
                return ResourceManager.GetString("FixedLabelWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flags {
            get {
                object obj = ResourceManager.GetObject("Flags", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generations:.
        /// </summary>
        internal static string GenerationsAre {
            get {
                return ResourceManager.GetString("GenerationsAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiation Term:.
        /// </summary>
        internal static string InitiationTermIs {
            get {
                return ResourceManager.GetString("InitiationTermIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string LastNameIs {
            get {
                return ResourceManager.GetString("LastNameIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to select and edit.
        /// </summary>
        internal static string LeftClickSelectEdit {
            get {
                return ResourceManager.GetString("LeftClickSelectEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Little(s):.
        /// </summary>
        internal static string LittlesAre {
            get {
                return ResourceManager.GetString("LittlesAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make This Tree Parent.
        /// </summary>
        internal static string MakeTheTreeParent {
            get {
                return ResourceManager.GetString("MakeTheTreeParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraterni.
        /// </summary>
        internal static string MaleName {
            get {
                return ResourceManager.GetString("MaleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members Without Bigs:.
        /// </summary>
        internal static string MembersWithNoBigs {
            get {
                return ResourceManager.GetString("MembersWithNoBigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyTree.
        /// </summary>
        internal static string MyTree {
            get {
                return ResourceManager.GetString("MyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (1}.
        /// </summary>
        internal static string NameConstructor {
            get {
                return ResourceManager.GetString("NameConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Generation.
        /// </summary>
        internal static string NextGeneration {
            get {
                return ResourceManager.GetString("NextGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Removal Confirmation.
        /// </summary>
        internal static string NodeRemovalConfirmation {
            get {
                return ResourceManager.GetString("NodeRemovalConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Node Name.
        /// </summary>
        internal static string ParentNodeName {
            get {
                return ResourceManager.GetString("ParentNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Generation.
        /// </summary>
        internal static string PreviousGeneration {
            get {
                return ResourceManager.GetString("PreviousGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FraterniTree.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the full name of {0}\&apos;s Big:.
        /// </summary>
        internal static string PromptUserForFullName {
            get {
                return ResourceManager.GetString("PromptUserForFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the parent XML node...\n Example: &quot;DeltaSigmaPhi-AlphaEta&quot;.
        /// </summary>
        internal static string PromptUSerForParentNodeName {
            get {
                return ResourceManager.GetString("PromptUSerForParentNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Node.
        /// </summary>
        internal static string RemoveNode {
            get {
                return ResourceManager.GetString("RemoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the exported xml as....
        /// </summary>
        internal static string SaveAsXml {
            get {
                return ResourceManager.GetString("SaveAsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;Image as....
        /// </summary>
        internal static string SaveImageAs {
            get {
                return ResourceManager.GetString("SaveImageAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save XML.
        /// </summary>
        internal static string SaveXml {
            get {
                return ResourceManager.GetString("SaveXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sibling Spacing:.
        /// </summary>
        internal static string SiblingSpacing {
            get {
                return ResourceManager.GetString("SiblingSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sister.
        /// </summary>
        internal static string Sister {
            get {
                return ResourceManager.GetString("Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        internal static string Spring {
            get {
                return ResourceManager.GetString("Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Brothers (Last, First, IniMonth, IniYear, Big, NextSibling, FirstLittle) VALUES (@Last, @First, @IniMonth, @IniYear, @Big, @NextSibling, @FirstLittle) ON DUPLICATE KEY UPDATE IniMonth=values(IniMonth), IniYear=values(IniYear), Big=values(Big), NextSibling=values(NextSibling), FirstLittle=values(FirstLittle).
        /// </summary>
        internal static string SQLInsertIntoBrothers {
            get {
                return ResourceManager.GetString("SQLInsertIntoBrothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Brothers.
        /// </summary>
        internal static string SQLSelectAllBrothers {
            get {
                return ResourceManager.GetString("SQLSelectAllBrothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtree Spacing:.
        /// </summary>
        internal static string SubtreeSpacing {
            get {
                return ResourceManager.GetString("SubtreeSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Hide Descendants.
        /// </summary>
        internal static string ToggleDescendants {
            get {
                return ResourceManager.GetString("ToggleDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to toggle tree view..
        /// </summary>
        internal static string ToggleTreeView {
            get {
                return ResourceManager.GetString("ToggleTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        internal static string Tree {
            get {
                return ResourceManager.GetString("Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree Parent:.
        /// </summary>
        internal static string TreeParent {
            get {
                return ResourceManager.GetString("TreeParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UpToParent {
            get {
                object obj = ResourceManager.GetObject("UpToParent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.0.
        /// </summary>
        internal static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Spacing:.
        /// </summary>
        internal static string VerticalSpacing {
            get {
                return ResourceManager.GetString("VerticalSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        internal static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Document|*.xml|All Files|*.*.
        /// </summary>
        internal static string XMLDocumentFilter {
            get {
                return ResourceManager.GetString("XMLDocumentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-8.
        /// </summary>
        internal static string XmlEncoding {
            get {
                return ResourceManager.GetString("XmlEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string XmlVersion {
            get {
                return ResourceManager.GetString("XmlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom &amp;In.
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom &amp;Out.
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
